[package]
name = "keystone"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["examples/hello_world", "keystone-macros"]

[dependencies]
axum = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
openapiv3 = "2.0"
keystone-macros = { path = "keystone-macros" }
schemars = { version = "0.8", features = ["preserve_order"] }
tower = "0.5"
tower-service = "0.3"
http = "1.0"
inventory = "0.3"
